[package]
name = "wist-exec"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
wist-contracts = { path = "../../../wist-contracts" }
wist-shared = { path = "../../../wist-shared" }
wist-validate = { path = "../../../wist-validate" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "wist-exec"
path = "src/main.rs"
